//! Binary STL: the format with no magic, where the only self-statement is an arithmetic identity.
//!
//! `test/fixtures/tet.stl` and `many.stl` are written by meshio (`scripts/make-stl-fixtures.py`),
//! which then reads them back and asserts its own triangle count against the header. `normals.stl`
//! carries the two shapes real writers differ on - a zeroed normal and one that points the wrong way
//! - assembled by that script rather than by a mesh library, because no library here is asked to make
//! them.
//!
//! A stored normal is never assumed correct, so the report lists what the file says and separately
//! counts how many disagree with the normal the triangle's three points imply.

use apk_lens::containers::{at, count, kind, name, parse, FORMAT_STL};
use std::fs;

const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../test/fixtures/");

fn fixture(file: &str) -> Vec<u8> {
    let path = format!("{FIXTURES}{file}");
    fs::read(&path).unwrap_or_else(|error| {
        panic!("{path} missing, run temp/venv/Scripts/python.exe scripts/make-stl-fixtures.py: {error}")
    })
}

fn report() -> Vec<String> {
    (0..count()).filter_map(at).collect()
}

fn rows(file: &str) -> Vec<String> {
    let bytes = fixture(file);
    assert_eq!(parse(&bytes), FORMAT_STL, "{file} is a binary STL");
    assert_eq!(kind(), FORMAT_STL, "kind() must agree with the return code");
    assert_eq!(name(), "stl", "the reader has to name what it walked");
    report()
}

fn value(parts: &[f32]) -> Vec<u8> {
    parts.iter().flat_map(|part| part.to_le_bytes()).collect()
}

fn triangle(normal: [f32; 3], a: [f32; 3], b: [f32; 3], c: [f32; 3]) -> Vec<u8> {
    let mut out = value(&normal);
    out.extend_from_slice(&value(&a));
    out.extend_from_slice(&value(&b));
    out.extend_from_slice(&value(&c));
    out.extend_from_slice(&0u16.to_le_bytes());
    out
}

/// Two real triangles under a header that claims ten, which is the case the size row exists for.
fn liar() -> Vec<u8> {
    let mut out = b"two of ten".to_vec();
    // NUL padding, because the reader trims the dots it substitutes for it and so names the header
    // exactly as it was written.
    out.resize(80, 0);
    out.extend_from_slice(&10u32.to_le_bytes());
    out.extend_from_slice(&triangle(
        [0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
    ));
    out.extend_from_slice(&triangle(
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0],
    ));
    out
}

#[test]
fn reads_the_tetrahedron_meshio_wrote() {
    assert_eq!(
        rows("tet.stl"),
        vec![
            "stl\t284\ttris\t4\tbroken\t0\tsolid\tThis file was generated by meshio v5.3.5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "sizes\tdeclared\t284\tactual\t284\tfit\texact",
            "tri\t0\tnormal\t0.000000,0.000000,1.000000\tv0\t0.000000,0.000000,0.000000\tv1\t1.000000,0.000000,0.000000\tv2\t0.000000,1.000000,0.000000\tattr\t0",
            "tri\t1\tnormal\t0.000000,-1.000000,0.000000\tv0\t0.000000,0.000000,0.000000\tv1\t1.000000,0.000000,0.000000\tv2\t0.000000,0.000000,1.000000\tattr\t0",
            "tri\t2\tnormal\t1.000000,0.000000,0.000000\tv0\t0.000000,0.000000,0.000000\tv1\t0.000000,1.000000,0.000000\tv2\t0.000000,0.000000,1.000000\tattr\t0",
            "tri\t3\tnormal\t0.577350,0.577350,0.577350\tv0\t1.000000,0.000000,0.000000\tv1\t0.000000,1.000000,0.000000\tv2\t0.000000,0.000000,1.000000\tattr\t0",
            "box\tmin\t0.000000,0.000000,0.000000\tmax\t1.000000,1.000000,1.000000",
            "normals\tzero\t0\twrong\t0\tcounted\t4",
            "walked\tend",
        ]
    );
}

#[test]
fn a_mesh_bigger_than_the_listing_is_counted_not_dumped() {
    let lines = rows("many.stl");
    assert_eq!(
        lines[0],
        "stl\t36184\ttris\t722\tbroken\t0\tsolid\tThis file was generated by meshio v5.3.5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    );
    assert_eq!(
        lines
            .iter()
            .filter(|line| line.starts_with("tri\t"))
            .count(),
        16,
        "the list is capped but the count above it is not"
    );
    assert_eq!(lines[18], "cut\ttris\t722");
    assert_eq!(
        lines[19],
        "box\tmin\t0.000000,0.000000,0.000000\tmax\t2.000000,0.250000,0.625000"
    );
    assert_eq!(lines[20], "normals\tzero\t0\twrong\t0\tcounted\t16");
    assert_eq!(lines[21], "walked\tend");
}

#[test]
fn a_zeroed_normal_and_a_flipped_one_are_told_apart() {
    let lines = rows("normals.stl");
    assert!(
        lines[0].starts_with("stl\t184\ttris\t2\tbroken\t0\tsolid\tnormals probe"),
        "{:?}",
        lines[0]
    );
    assert_eq!(
        lines[2],
        "tri\t0\tnormal\t0.000000,0.000000,0.000000\tv0\t0.000000,0.000000,0.000000\tv1\t1.000000,0.000000,0.000000\tv2\t0.000000,1.000000,0.000000\tattr\t0"
    );
    assert_eq!(
        lines[3],
        "tri\t1\tnormal\t-0.577350,-0.577350,-0.577350\tv0\t1.000000,0.000000,0.000000\tv1\t0.000000,1.000000,0.000000\tv2\t0.000000,0.000000,1.000000\tattr\t0"
    );
    assert_eq!(
        lines[lines.len() - 2],
        "normals\tzero\t1\twrong\t1\tcounted\t2",
        "one is missing, one points the other way, and those are different facts"
    );
}

#[test]
fn a_count_that_lies_about_the_size_is_reported_rather_than_walked() {
    let bytes = liar();
    assert_eq!(parse(&bytes), FORMAT_STL, "{} bytes", bytes.len());
    let lines = report();
    assert_eq!(lines[0], "stl\t184\ttris\t10\tbroken\t1\tsolid\ttwo of ten");
    assert_eq!(lines[1], "sizes\tdeclared\t584\tactual\t184\tfit\tlong");
    assert_eq!(
        lines
            .iter()
            .filter(|line| line.starts_with("tri\t"))
            .count(),
        2,
        "only the triangles that are really there are listed"
    );
    assert_eq!(lines[4], "cut\ttris\t10");
    assert_eq!(lines[lines.len() - 1], "stopped\tbroken\t1");
}

#[test]
fn text_stl_and_unrelated_bytes_are_not_claimed_as_binary() {
    // magika's label is about the binary encoding; the ASCII form is a different document, and its
    // bytes read as denormal floats rather than as a unit normal, which is what turns it down here.
    let ascii = b"solid widget\n  facet normal 0 0 1\n    outer loop\n     vertex 0 0 0\n    end loop\n  end facet\nendsolid widget\n";
    assert_ne!(parse(ascii), FORMAT_STL, "an ASCII STL is not this format");
    assert_eq!(parse(&[0u8; 400]), -2, "zeroes name no triangles at all");
    assert_eq!(
        parse(&liar()[..120]),
        -2,
        "below one whole triangle there is nothing to count"
    );
    assert_eq!(parse(b"aaaaaaaa"), -2, "eight bytes name no triangles");

    // A header whose count is huge would ask for a 12 MB mesh from a 184-byte file.
    let mut greedy = liar();
    greedy[80..84].copy_from_slice(&2_000_000_000u32.to_le_bytes());
    assert_ne!(
        parse(&greedy),
        FORMAT_STL,
        "an implausible count is not believed"
    );
}
