"""Writes test/fixtures/tiny.tar and tiny.wav with Python's own tarfile and wave modules.

Deliberately not written by this repo's code: the container reader tests assert against files
produced by an independent implementation of the format, so a shared misunderstanding of the
layout cannot make both sides agree. The generated bytes are committed; CI reads them as-is.
"""
import io
import os
import zipfile
import tarfile
import wave

out = os.path.join(os.path.dirname(__file__), '..', 'test', 'fixtures')
os.makedirs(out, exist_ok=True)

with tarfile.open(os.path.join(out, 'tiny.tar'), 'w') as archive:
    for name, data in (('hello.txt', b'lyco\n'), ('dir/note.txt', b'second member\n')):
        info = tarfile.TarInfo(name)
        info.size = len(data)
        info.mode = 0o644
        info.uid = 0
        info.gid = 0
        info.mtime = 1700000000
        archive.addfile(info, io.BytesIO(data))

with wave.open(os.path.join(out, 'tiny.wav'), 'wb') as handle:
    handle.setnchannels(1)
    handle.setsampwidth(1)
    handle.setframerate(8000)
    handle.writeframes(bytes(range(0, 64)))

print('wrote tiny.tar and tiny.wav')

# Pillow writes the WebP and reads it back; the reader under test walks the same bytes.
from PIL import Image  # noqa: E402

Image.new('RGB', (5, 3), (200, 30, 90)).save(os.path.join(out, 'tiny.webp'), format='WEBP', lossless=True)
print('wrote tiny.webp')

# GNU tar and Pillow are the producers here on purpose: an independent writer means the reader
# cannot agree with itself. gnu.tar wraps the TIFF so its member listing is also third-party output.
import subprocess  # noqa: E402

from PIL import Image  # noqa: E402

tiff_path = os.path.join(out, 'tiny.tif')
Image.new('RGB', (3, 2), (10, 120, 240)).save(tiff_path, compression='none', dpi=(72, 72))

tar_path = os.path.join(out, 'gnu.tar')
subprocess.run(
    ['tar', '-cf', tar_path, '--format=ustar', '--owner=0', '--group=0', '--mtime=@1700000000',
     '--directory', out, 'tiny.tif'],
    check=True,
)
print('wrote tiny.tif and gnu.tar (GNU tar)')

# Pillow's JPEG and Python's zipfile are the independent producers for the generated Kaitai
# readers' assertions: the marker list and the central-directory counts below come from what those
# two write, not from anything this repo controls.
Image.new('RGB', (4, 3), (30, 200, 90)).save(os.path.join(out, 'tiny.jpg'), format='JPEG', quality=90)

with zipfile.ZipFile(os.path.join(out, 'tiny.zip'), 'w', zipfile.ZIP_DEFLATED) as archive:
    archive.writestr('a.txt', b'alpha' * 4)
    archive.writestr('nested/b.bin', bytes(range(20)))
print('wrote tiny.jpg and tiny.zip')
