"""Writes test/fixtures/tiny.tar and tiny.wav with Python's own tarfile and wave modules.

Deliberately not written by this repo's code: the container reader tests assert against files
produced by an independent implementation of the format, so a shared misunderstanding of the
layout cannot make both sides agree. The generated bytes are committed; CI reads them as-is.
"""
import io
import os
import tarfile
import wave

out = os.path.join(os.path.dirname(__file__), '..', 'test', 'fixtures')
os.makedirs(out, exist_ok=True)

with tarfile.open(os.path.join(out, 'tiny.tar'), 'w') as archive:
    for name, data in (('hello.txt', b'lyco\n'), ('dir/note.txt', b'second member\n')):
        info = tarfile.TarInfo(name)
        info.size = len(data)
        info.mode = 0o644
        info.uid = 0
        info.gid = 0
        info.mtime = 1700000000
        archive.addfile(info, io.BytesIO(data))

with wave.open(os.path.join(out, 'tiny.wav'), 'wb') as handle:
    handle.setnchannels(1)
    handle.setsampwidth(1)
    handle.setframerate(8000)
    handle.writeframes(bytes(range(0, 64)))

print('wrote tiny.tar and tiny.wav')
