<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="c00" type="xs:string"/>
  <xs:element name="c01" type="xs:string"/>
  <xs:element name="c02" type="xs:string"/>
  <xs:element name="c03" type="xs:string"/>
  <xs:element name="c04" type="xs:string"/>
  <xs:element name="c05" type="xs:string"/>
  <xs:element name="c06" type="xs:string"/>
  <xs:element name="c07" type="xs:string"/>
  <xs:element name="c08" type="xs:string"/>
  <xs:element name="c09" type="xs:string"/>
  <xs:element name="c10" type="xs:string"/>
  <xs:element name="c11" type="xs:string"/>
  <xs:element name="c12" type="xs:string"/>
  <xs:element name="c13" type="xs:string"/>
  <xs:element name="c14" type="xs:string"/>
  <xs:element name="c15" type="xs:string"/>
  <xs:element name="c16" type="xs:string"/>
  <xs:element name="c17" type="xs:string"/>
  <xs:element name="c18" type="xs:string"/>
  <xs:element name="c19" type="xs:string"/>
  <xs:element name="c20" type="xs:string"/>
  <xs:element name="c21" type="xs:string"/>
  <xs:element name="c22" type="xs:string"/>
  <xs:element name="c23" type="xs:string"/>
  <xs:element name="c24" type="xs:string"/>
  <xs:element name="c25" type="xs:string"/>
  <xs:element name="c26" type="xs:string"/>
  <xs:element name="c27" type="xs:string"/>
  <xs:element name="c28" type="xs:string"/>
  <xs:element name="c29" type="xs:string"/>
  <xs:element name="c30" type="xs:string"/>
  <xs:element name="c31" type="xs:string"/>
  <xs:element name="c32" type="xs:string"/>
  <xs:element name="c33" type="xs:string"/>
  <xs:element name="c34" type="xs:string"/>
  <xs:element name="c35" type="xs:string"/>
  <xs:element name="c36" type="xs:string"/>
  <xs:element name="c37" type="xs:string"/>
  <xs:element name="c38" type="xs:string"/>
  <xs:element name="c39" type="xs:string"/>
  <xs:element name="c40" type="xs:string"/>
  <xs:element name="c41" type="xs:string"/>
  <xs:element name="c42" type="xs:string"/>
  <xs:element name="c43" type="xs:string"/>
  <xs:element name="c44" type="xs:string"/>
  <xs:element name="c45" type="xs:string"/>
  <xs:element name="c46" type="xs:string"/>
  <xs:element name="c47" type="xs:string"/>
  <xs:element name="c48" type="xs:string"/>
  <xs:element name="c49" type="xs:string"/>
  <xs:element name="c50" type="xs:string"/>
  <xs:element name="c51" type="xs:string"/>
  <xs:element name="c52" type="xs:string"/>
  <xs:element name="c53" type="xs:string"/>
  <xs:element name="c54" type="xs:string"/>
  <xs:element name="c55" type="xs:string"/>
  <xs:element name="c56" type="xs:string"/>
  <xs:element name="c57" type="xs:string"/>
  <xs:element name="c58" type="xs:string"/>
  <xs:element name="c59" type="xs:string"/>
  <xs:element name="c60" type="xs:string"/>
  <xs:element name="c61" type="xs:string"/>
  <xs:element name="c62" type="xs:string"/>
  <xs:element name="c63" type="xs:string"/>
  <xs:element name="c64" type="xs:string"/>
  <xs:element name="c65" type="xs:string"/>
  <xs:element name="c66" type="xs:string"/>
  <xs:element name="c67" type="xs:string"/>
  <xs:element name="c68" type="xs:string"/>
  <xs:element name="c69" type="xs:string"/>
</xs:schema>
